### ISSUE TITLE
xxx vod+radio from all over the world

### ISSUE THREAD

**Issue by BillakosGR** [freearhey/iptv#175]
I got 2 m3us.One with tons of xxx vod and one with radio from all over the world.Can I somehow send them to you on private?

**Comment by freearhey** [comment]
Yes of course. You can send it to the email specified in my profile. But I want to warn you that I can’t post this playlist here since only live TV broadcasts are published in this repository.

**Comment by BillakosGR** [comment]
You cant add XXX vod and international radio??I think that should be a great feature for the playlist.

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by freearhey** [comment]
Personally, I think that it is better if this repository is dedicated only to live TV broadcasts, otherwise it will be too difficult to maintain it in order. Perhaps the best solution would be to create a separate repository for VOD and another for Radio.

But this is only my opinion, it would be interesting to hear the opinion of other members of the community.

**Comment by 1000mbps** [comment]
While it's better if they're all in one I'd agree that it's better to have them separate, especially if that makes it easier to organise

**Comment by BillakosGR** [comment]
I will suggest one playlist with: Vod+xxx Vod and one playlist with: Radio+CCTV.

**Comment by muratrota55** [comment]
> Ben 2 m3us var.Bir ton xxx vod ve bir de dünyanın dört bir yanından gelen radyo ile. Bir şekilde onları size özel olarak gönderebilir miyim? 

hi could you send me as m3u file.

**Comment by freearhey** [comment]
@muratrota55 I think you should ask @BillakosGR for this.
