### ISSUE TITLE
Test file

### ISSUE THREAD

**Issue by mohsin1122** [freearhey/iptv#5]
How to use the test file to test working links. 
Plz help

**Comment by freearhey** [comment]
Go to the `iptv` folder and type `npm run test` at the command line. Be prepared it may take a long time. 
After the tests end all broken links will be saved to the file `error.log`.

**Comment by Mamon44** [comment]
Bonjour s'il vous plaît est-ce que vous avez la liste française BeIn Sport RMC du canal cinéma merci Hello please do you have the French list BeIn Sport RMC channel cinema thank you

**Comment by OtakuNami** [comment]
This works great thanks Can u add all USA/Canada channels i noticed CBS is missing(non news version)

**Comment by Mamon44** [comment]
Hello I think she misses bein sports channel + Canalsat channel cinema emotion RMC in France is it possible -------- Message original --------Objet : Re: [freearhey/iptv] Test file (#5)De : OtakuNami À : freearhey/iptv Cc : Mamon44 ,Comment This works great thanks Can u add all USA/Canada channels i noticed CBS is missing(non news version)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freearhey/iptv","title":"freearhey/iptv","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/freearhey/iptv"}},"updates":{"snippets":[{"icon":"PERSON","message":"@OtakuNami in #5: This works great thanks Can u add all USA/Canada channels i noticed CBS is missing(non news version)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/freearhey/iptv/issues/5#issuecomment-483090202"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/freearhey/iptv/issues/5#issuecomment-483090202",
"url": "https://github.com/freearhey/iptv/issues/5#issuecomment-483090202",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mohsin1122** [comment]
#in.m3u
FAILURES! (1 tests, 151 channels, 25 failures)

**Comment by freearhey** [comment]
@mohsin1122 I removed most of the broken links. Now the errors should disappear.
